maquina1.setDrop(a);
    	maquina2.setDrop(b);
    	maquina3.setDrop(c);
    	maquina4.setDrop(d);
    	maquina5.setDrop(e);
    	maquina6.setDrop(f);
    	maquina7.setDrop(g);
    	maquina8.setDrop(h);
    	maquina9.setDrop(i);
    	maquina10.setDrop(j);
    	maquina11.setDrop(k);
    	maquina12.setDrop(l);
    	maquina13.setDrop(m);
    	maquina14.setDrop(n);
    	maquina15.setDrop(o);
    	maquina16.setDrop(p);
    	maquina17.setDrop(q);
    	maquina18.setDrop(r);
    	maquina19.setDrop(s);
    	maquina20.setDrop(t);
    	maquina21.setDrop(u);
    	maquina22.setDrop(v);
    	maquina23.setDrop(w);
    	maquina24.setDrop(x);
    	maquina25.setDrop(y);
    	maquina26.setDrop(z);
    	maquina27.setDrop(aa);
    	maquina28.setDrop(bb);
    	maquina29.setDrop(cc);
    	maquina30.setDrop(dd)