name: SoulthLogin
version: 1.0
author: Ninjay_
main: me.ninjay.loginsoulth.main.Main
commands: 
  login:
  register:
    aliases: [registrar]
  trocarsenha:
    aliases: [changepassword]
  setloginspawn: