name: SafeClub
version: 1.0
author: MyNameIsNinjay
main: me.ninjay.safeclub.main.Main
commands:
  evento:
  gladiator:
    aliases: [guerra]
  recompensa:
  lobby:
    aliases: [hub]
  setspawn:
  spawn:
  darcaixa:
  vip:
  kit:
  cash:
  