title: true
titlePrincipal: '&6KitPvP' 
titleSecundario: '&aServidor de pvp' 
mensagemAoEntrar: '&6%nick% Entrou no server !' 
nomeDoServidor: 'NinjaMC' 
vidaSopa: 3.5 
mensagemAoSair: '&6%nick% Saiu do server !' 
