twitter: twitter.com/SafeClub
discord: www.safeclub.com/discord
forum: www.safeclub.com/forum
loja: loja.safeclub.com
novidade: Factions OLD em breve!

TempoClearDrops: 60
TempoTirarSpawner: 20 #segundos