package me.ninjay.soulthmaquinas.estruturas;

import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

import me.ninjay.ninjaapi.utils.Mine;
import me.ninjay.soulthmaquinas.main.Main;
import net.eduard.api.lib.BukkitConfig;

public class MaquinaAPI {

	public static BukkitConfig config = new BukkitConfig("maquinas.yml", Main.getPlugin(Main.class));
	public static MaquinaManager manager;

	public static void reload() {
		config.reloadConfig();
		if (config.contains("maquinas")) {
			manager = (MaquinaManager) config.get("maquinas");
		} else {
			manager = new MaquinaManager();

			Maquina maquina1 = new Maquina();
			Maquina maquina2 = new Maquina();
			Maquina maquina3 = new Maquina();
			Maquina maquina4 = new Maquina();
			Maquina maquina5 = new Maquina();
			Maquina maquina6 = new Maquina();
			Maquina maquina7 = new Maquina();
			Maquina maquina8 = new Maquina();
			Maquina maquina9 = new Maquina();
			Maquina maquina10 = new Maquina();
			Maquina maquina11 = new Maquina();
			Maquina maquina12 = new Maquina();
			Maquina maquina13 = new Maquina();
			Maquina maquina14 = new Maquina();
			Maquina maquina15 = new Maquina();
			Maquina maquina16 = new Maquina();
			Maquina maquina17 = new Maquina();
			Maquina maquina18 = new Maquina();
			Maquina maquina19 = new Maquina();
			Maquina maquina20 = new Maquina();
			Maquina maquina21 = new Maquina();
			Maquina maquina22 = new Maquina();
			Maquina maquina23 = new Maquina();
			Maquina maquina24 = new Maquina();
			Maquina maquina25 = new Maquina();
			Maquina maquina26 = new Maquina();
			Maquina maquina27 = new Maquina();
			Maquina maquina28 = new Maquina();
			Maquina maquina29 = new Maquina();
			Maquina maquina30 = new Maquina();

			maquina1.setNome("1");
			maquina2.setNome("2");
			maquina3.setNome("3");
			maquina4.setNome("4");
			maquina5.setNome("5");
			maquina6.setNome("6");
			maquina7.setNome("7");
			maquina8.setNome("8");
			maquina9.setNome("9");
			maquina10.setNome("10");
			maquina11.setNome("11");
			maquina12.setNome("12");
			maquina13.setNome("13");
			maquina14.setNome("14");
			maquina15.setNome("15");
			maquina16.setNome("16");
			maquina17.setNome("17");
			maquina18.setNome("18");
			maquina19.setNome("19");
			maquina20.setNome("20");
			maquina21.setNome("21");
			maquina22.setNome("22");
			maquina23.setNome("23");
			maquina24.setNome("24");
			maquina25.setNome("25");
			maquina26.setNome("26");
			maquina27.setNome("27");
			maquina28.setNome("28");
			maquina29.setNome("29");
			maquina30.setNome("30");

			ItemStack a = Mine.newItem(Material.DIRT, "§eMaquina 01", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack b = Mine.newItem(Material.DIRT, "§eMaquina 02", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack c = Mine.newItem(Material.DIRT, "§eMaquina 03", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack d = Mine.newItem(Material.DIRT, "§eMaquina 04", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack e = Mine.newItem(Material.DIRT, "§eMaquina 05", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack f = Mine.newItem(Material.DIRT, "§eMaquina 06", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack g = Mine.newItem(Material.DIRT, "§eMaquina 07", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack h = Mine.newItem(Material.DIRT, "§eMaquina 08", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack i = Mine.newItem(Material.DIRT, "§eMaquina 09", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack j = Mine.newItem(Material.DIRT, "§eMaquina 10", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack k = Mine.newItem(Material.DIRT, "§eMaquina 11", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack l = Mine.newItem(Material.DIRT, "§eMaquina 12", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack m = Mine.newItem(Material.DIRT, "§eMaquina 13", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack n = Mine.newItem(Material.DIRT, "§eMaquina 14", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack o = Mine.newItem(Material.DIRT, "§eMaquina 15", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack p = Mine.newItem(Material.DIRT, "§eMaquina 16", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack q = Mine.newItem(Material.DIRT, "§eMaquina 17", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack r = Mine.newItem(Material.DIRT, "§eMaquina 18", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack s = Mine.newItem(Material.DIRT, "§eMaquina 19", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack t = Mine.newItem(Material.DIRT, "§eMaquina 20", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack u = Mine.newItem(Material.DIRT, "§eMaquina 21", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack v = Mine.newItem(Material.DIRT, "§eMaquina 22", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack w = Mine.newItem(Material.DIRT, "§eMaquina 23", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack x = Mine.newItem(Material.DIRT, "§eMaquina 24", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack y = Mine.newItem(Material.DIRT, "§eMaquina 25", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack z = Mine.newItem(Material.DIRT, "§eMaquina 26", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack aa = Mine.newItem(Material.DIRT, "§eMaquina 27", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack bb = Mine.newItem(Material.DIRT, "§eMaquina 28", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack cc = Mine.newItem(Material.DIRT, "§eMaquina 29", 1, 0," ","§ePara comprar mais utilize /maquina");
			ItemStack dd = Mine.newItem(Material.DIRT, "§eMaquina 30", 1, 0," ","§ePara comprar mais utilize /maquina");

			ItemStack ad = Mine.newItem(Material.DIRT, "§eDrop 01", 1, 0," ","§ePara coletar clique aqui");
			ItemStack bd = Mine.newItem(Material.DIRT, "§eDrop 02", 1, 0," ","§ePara coletar clique aqui");
			ItemStack cd = Mine.newItem(Material.DIRT, "§eDrop 03", 1, 0," ","§ePara coletar clique aqui");
			ItemStack dd1 = Mine.newItem(Material.DIRT, "§eDrop 04", 1, 0," ","§ePara coletar clique aqui");
			ItemStack ed = Mine.newItem(Material.DIRT, "§eDrop 05", 1, 0," ","§ePara coletar clique aqui");
			ItemStack fd = Mine.newItem(Material.DIRT, "§eDrop 06", 1, 0," ","§ePara coletar clique aqui");
			ItemStack gd = Mine.newItem(Material.DIRT, "§eDrop 07", 1, 0," ","§ePara coletar clique aqui");
			ItemStack hd = Mine.newItem(Material.DIRT, "§eDrop 08", 1, 0," ","§ePara coletar clique aqui");
			ItemStack id = Mine.newItem(Material.DIRT, "§eDrop 09", 1, 0," ","§ePara coletar clique aqui");
			ItemStack jd = Mine.newItem(Material.DIRT, "§eDrop 10", 1, 0," ","§ePara coletar clique aqui");
			ItemStack kd = Mine.newItem(Material.DIRT, "§eDrop 11", 1, 0," ","§ePara coletar clique aqui");
			ItemStack ld = Mine.newItem(Material.DIRT, "§eDrop 12", 1, 0," ","§ePara coletar clique aqui");
			ItemStack md = Mine.newItem(Material.DIRT, "§eDrop 13", 1, 0," ","§ePara coletar clique aqui");
			ItemStack nd = Mine.newItem(Material.DIRT, "§eDrop 14", 1, 0," ","§ePara coletar clique aqui");
			ItemStack od = Mine.newItem(Material.DIRT, "§eDrop 15", 1, 0," ","§ePara coletar clique aqui");
			ItemStack pd = Mine.newItem(Material.DIRT, "§eDrop 16", 1, 0," ","§ePara coletar clique aqui");
			ItemStack qd = Mine.newItem(Material.DIRT, "§eDrop 17", 1, 0," ","§ePara coletar clique aqui");
			ItemStack rd = Mine.newItem(Material.DIRT, "§eDrop 18", 1, 0," ","§ePara coletar clique aqui");
			ItemStack sd = Mine.newItem(Material.DIRT, "§eDrop 19", 1, 0," ","§ePara coletar clique aqui");
			ItemStack td = Mine.newItem(Material.DIRT, "§eDrop 20", 1, 0," ","§ePara coletar clique aqui");
			ItemStack ud = Mine.newItem(Material.DIRT, "§eDrop 21", 1, 0," ","§ePara coletar clique aqui");
			ItemStack vd = Mine.newItem(Material.DIRT, "§eDrop 22", 1, 0," ","§ePara coletar clique aqui");
			ItemStack wd = Mine.newItem(Material.DIRT, "§eDrop 23", 1, 0," ","§ePara coletar clique aqui");
			ItemStack xd = Mine.newItem(Material.DIRT, "§eDrop 24", 1, 0," ","§ePara coletar clique aqui");
			ItemStack yd = Mine.newItem(Material.DIRT, "§eDrop 25", 1, 0," ","§ePara coletar clique aqui");
			ItemStack zd = Mine.newItem(Material.DIRT, "§eDrop 26", 1, 0," ","§ePara coletar clique aqui");
			ItemStack aad = Mine.newItem(Material.DIRT, "§eDrop 27", 1, 0," ","§ePara coletar clique aqui");
			ItemStack bbd = Mine.newItem(Material.DIRT, "§eDrop 28", 1, 0," ","§ePara coletar clique aqui");
			ItemStack ccd = Mine.newItem(Material.DIRT, "§eDrop 29", 1, 0," ","§ePara coletar clique aqui");
			ItemStack dd2 = Mine.newItem(Material.DIRT, "§eDrop 30", 1, 0," ","§ePara coletar clique aqui");

			maquina1.setIcone(a);
			maquina2.setIcone(b);
			maquina3.setIcone(c);
			maquina4.setIcone(d);
			maquina5.setIcone(e);
			maquina6.setIcone(f);
			maquina7.setIcone(g);
			maquina8.setIcone(h);
			maquina9.setIcone(i);
			maquina10.setIcone(j);
			maquina11.setIcone(k);
			maquina12.setIcone(l);
			maquina13.setIcone(m);
			maquina14.setIcone(n);
			maquina15.setIcone(o);
			maquina16.setIcone(p);
			maquina17.setIcone(q);
			maquina18.setIcone(r);
			maquina19.setIcone(s);
			maquina20.setIcone(t);
			maquina21.setIcone(u);
			maquina22.setIcone(v);
			maquina23.setIcone(w);
			maquina24.setIcone(x);
			maquina25.setIcone(y);
			maquina26.setIcone(z);
			maquina27.setIcone(aa);
			maquina28.setIcone(bb);
			maquina29.setIcone(cc);
			maquina30.setIcone(dd);

			maquina1.setDrop(ad);
			maquina2.setDrop(bd);
			maquina3.setDrop(cd);
			maquina4.setDrop(dd1);
			maquina5.setDrop(ed);
			maquina6.setDrop(fd);
			maquina7.setDrop(gd);
			maquina8.setDrop(hd);
			maquina9.setDrop(id);
			maquina10.setDrop(jd);
			maquina11.setDrop(kd);
			maquina12.setDrop(ld);
			maquina13.setDrop(md);
			maquina14.setDrop(nd);
			maquina15.setDrop(od);
			maquina16.setDrop(pd);
			maquina17.setDrop(qd);
			maquina18.setDrop(rd);
			maquina19.setDrop(sd);
			maquina20.setDrop(td);
			maquina21.setDrop(ud);
			maquina22.setDrop(vd);
			maquina23.setDrop(wd);
			maquina24.setDrop(xd);
			maquina25.setDrop(yd);
			maquina26.setDrop(zd);
			maquina27.setDrop(aad);
			maquina28.setDrop(bbd);
			maquina29.setDrop(ccd);
			maquina30.setDrop(dd2);

			maquina1.setValor((double) 1);
			maquina2.setValor((double) 1);
			maquina3.setValor((double) 1);
			maquina4.setValor((double) 1);
			maquina5.setValor((double) 1);
			maquina6.setValor((double) 1);
			maquina7.setValor((double) 1);
			maquina8.setValor((double) 1);
			maquina9.setValor((double) 1);
			maquina10.setValor((double) 1);
			maquina11.setValor((double) 1);
			maquina12.setValor((double) 1);
			maquina13.setValor((double) 1);
			maquina14.setValor((double) 1);
			maquina15.setValor((double) 1);
			maquina16.setValor((double) 1);
			maquina17.setValor((double) 1);
			maquina18.setValor((double) 1);
			maquina19.setValor((double) 1);
			maquina20.setValor((double) 1);
			maquina21.setValor((double) 1);
			maquina22.setValor((double) 1);
			maquina23.setValor((double) 1);
			maquina24.setValor((double) 1);
			maquina25.setValor((double) 1);
			maquina26.setValor((double) 1);
			maquina27.setValor((double) 1);
			maquina28.setValor((double) 1);
			maquina29.setValor((double) 1);
			maquina30.setValor((double) 1);
			
			maquina1.setValordrop((double) 1);
			maquina2.setValordrop((double) 1);
			maquina3.setValordrop((double) 1);
			maquina4.setValordrop((double) 1);
			maquina5.setValordrop((double) 1);
			maquina6.setValordrop((double) 1);
			maquina7.setValordrop((double) 1);
			maquina8.setValordrop((double) 1);
			maquina9.setValordrop((double) 1);
			maquina10.setValordrop((double) 1);
			maquina11.setValordrop((double) 1);
			maquina12.setValordrop((double) 1);
			maquina13.setValordrop((double) 1);
			maquina14.setValordrop((double) 1);
			maquina15.setValordrop((double) 1);
			maquina16.setValordrop((double) 1);
			maquina17.setValordrop((double) 1);
			maquina18.setValordrop((double) 1);
			maquina19.setValordrop((double) 1);
			maquina20.setValordrop((double) 1);
			maquina21.setValordrop((double) 1);
			maquina22.setValordrop((double) 1);
			maquina23.setValordrop((double) 1);
			maquina24.setValordrop((double) 1);
			maquina25.setValordrop((double) 1);
			maquina26.setValordrop((double) 1);
			maquina27.setValordrop((double) 1);
			maquina28.setValordrop((double) 1);
			maquina29.setValordrop((double) 1);
			maquina30.setValordrop((double) 1);
			
			manager.getMaquinas().add(maquina1);
			manager.getMaquinas().add(maquina2);
			manager.getMaquinas().add(maquina3);
			manager.getMaquinas().add(maquina4);
			manager.getMaquinas().add(maquina5);
			manager.getMaquinas().add(maquina6);
			manager.getMaquinas().add(maquina7);
			manager.getMaquinas().add(maquina8);
			manager.getMaquinas().add(maquina9);
			manager.getMaquinas().add(maquina10);
			manager.getMaquinas().add(maquina11);
			manager.getMaquinas().add(maquina12);
			manager.getMaquinas().add(maquina13);
			manager.getMaquinas().add(maquina14);
			manager.getMaquinas().add(maquina15);
			manager.getMaquinas().add(maquina16);
			manager.getMaquinas().add(maquina17);
			manager.getMaquinas().add(maquina18);
			manager.getMaquinas().add(maquina19);
			manager.getMaquinas().add(maquina20);
			manager.getMaquinas().add(maquina21);
			manager.getMaquinas().add(maquina22);
			manager.getMaquinas().add(maquina23);
			manager.getMaquinas().add(maquina24);
			manager.getMaquinas().add(maquina25);
			manager.getMaquinas().add(maquina26);
			manager.getMaquinas().add(maquina27);
			manager.getMaquinas().add(maquina28);
			manager.getMaquinas().add(maquina29);
			manager.getMaquinas().add(maquina30);
			save();
		}
	}
	public static void save() {
		config.set("maquinas", manager);
		config.saveConfig();
	}
}
