name: TaaSafeSurvival
version: 1.0
author: Ninjay_
main: me.ninjay.safesurvival.main.Main
commands:
  spawn:
  tpa:
   aliases: [teleporte]
  tpaccept:
   aliases: [tpaceitar,tpaaccept,tpaaceitar]
  tpacancel:
   aliases: [tpacancelar,tpcancel,tpcancelar]
  