name: RankUPAurea
version: 1.0
author: Ninjay_
main: me.ninjay.aureaup.main.Main
commands:
  login:
    aliases: [logar]
  register:
    aliases: [registrar]
  trocarsenha:
    aliases: [changeepassword]