name: SafeEventos
version: 1.0
author: MyNameIsNinjay
main: me.ninjay.safeeventos.main.Main
commands:
  eventos:
   aliases: [evento]
  baseperdida:
   aliases: [bp]
  loteria:
  bolao:
   aliases: [bolão]
  palavra:
  sorteio:
  guerra: