name: NinjaRadomPlugins
version: 1.0
author: Ninjay_
main: me.ninjay.random.main.Main
depend: [CursoAPI]
commands:
  sorteio:
  bolao:
  xp:
  encantar:
  mensagem:
  holograma:
  score:
  zombie:
  luz: